all:
	cargo run
d:
	rust-gdb ../target/debug/atcoder_agc_agc033_a_300_darker_and_darker -x gdbrc.py
r:
	cargo run --release
t:
	cargo test
	rust in01.rs | cargo run --release
tb:
	RUST_BACKTRACE=1 cargo test
